const express= require('express');
const router= express.Router();
//bringing in the registration model for drugs passing the registration date and time is generated by the system using Date.now() as default
const drugs= require('../model/drug');

//a post request to record quantity of drugs sent to all local government
router.post('/', (req,res,next)=>{
    let drug= new drugs()

   drug.drug_name=req.body.drug_name,
    drug.name=req.body.name,
    drug.lga_name= req.body.lga_name,
    drug.quantity= req.body.quantity

    drugs.updateDrug(drug,(err,drug)=>{
        res.send('record taken on the admin page')
    })
});


module.exports= router